# Generated by Django 5.1.4 on 2025-03-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='default_shipping_address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
