# Generated by Django 5.1.4 on 2025-03-25 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='user_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
