# Generated by Django 5.1.4 on 2025-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_is_refunded_order_razorpay_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='price_at_purchase',
            field=models.DecimalField(decimal_places=2, help_text='Stores the offer price at purchase', max_digits=10),
        ),
    ]