# Generated by Django 5.1.4 on 2025-05-05 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedimage',
            name='type',
            field=models.CharField(choices=[('normal', 'Normal'), ('carousel', 'Carousel')], default='normal', max_length=20),
        ),
    ]
